---
# tasks file for dnsmasq
- name: install dnsmasq
  package:
    name: dnsmasq
    state: present
- name: upload dnsmasq config file
  copy:
    src: "{{ role_dir + files_dir + conf_file_path }}"
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: 0644
  notify: restart dnsmasq
